# Generated by Django 5.0.1 on 2024-01-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('effieciency', models.CharField(max_length=30)),
                ('top_speed', models.CharField(max_length=30)),
                ('battery_range', models.CharField(max_length=30)),
                ('fast_charge', models.CharField(max_length=20)),
                ('released_date', models.DateField()),
            ],
        ),
    ]
