# Generated by Django 5.0.1 on 2024-01-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latestevs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evs',
            new_name='Ev',
        ),
    ]
