# Generated by Django 5.0.1 on 2024-01-06 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("latestevs", "0002_rename_evs_ev"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ev",
            old_name="effieciency",
            new_name="efficiency",
        ),
    ]
