# Generated by Django 5.0.1 on 2024-01-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("latestevs", "0003_rename_effieciency_ev_efficiency"),
    ]

    operations = [
        migrations.AddField(
            model_name="ev",
            name="average_price",
            field=models.CharField(default="$ 0", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ev",
            name="seats",
            field=models.IntegerField(
                choices=[
                    (2, "Two"),
                    (4, "Four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                    (8, "eight"),
                    (9, "nine"),
                ],
                default=2,
            ),
        ),
    ]
