# Generated by Django 5.0.1 on 2024-01-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("latestevs", "0004_ev_average_price_ev_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ev",
            name="seats",
            field=models.IntegerField(
                choices=[
                    (2, "Two"),
                    (4, "Four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                    (8, "eight"),
                    (9, "nine"),
                ],
                default=5,
            ),
        ),
    ]
