# Generated by Django 5.0.1 on 2024-01-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("latestevs", "0005_alter_ev_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ev",
            name="seats",
            field=models.IntegerField(
                choices=[
                    (2, "Two"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                    (9, "Nine"),
                ],
                default=(5, "five"),
            ),
        ),
    ]
